name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install depends
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl1.2-dev libvorbis-dev libsdl-image1.2-dev
    - name: make
      run: make -f Makefile-C
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: /home/runner/work/glfrontier/glfrontier/
