name: Windows Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: false  # Disable automatic update during setup
    - name: Install depends
      shell: msys2 {0}
      run: |
        pacman --noconfirm -S mingw-w64-i686-toolchain
        pacman --noconfirm -S mingw-w64-i686-SDL
        pacman --noconfirm -S mingw-w64-i686-SDL_image
        pacman --noconfirm -S mingw-w64-i686-libvorbis
    - name: mingw32-make
      run: mingw32-make -f Makefile-mingw
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: D:/a/glfrontier/glfrontier
