name: Windows Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
    - name: Install Depends
      shell: msys2 {0}
      run: |
        pacman --noconfirm -S --needed base-devel
        pacman --noconfirm -S --needed mingw-w64-i686-toolchain
        pacman --noconfirm -S --needed mingw-w64-i686-gcc
        pacman --noconfirm -S --needed mingw-w64-i686-SDL
        pacman --noconfirm -S --needed mingw-w64-i686-SDL_image
        pacman --noconfirm -S --needed mingw-w64-i686-libvorbis
    - name: Setup environment variables
      shell: bash
      run: set PATH=$PATH"C:\msys64\mingw32\bin";
    - name: Compile
      run: mingw32-make -f Makefile-mingw
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: D:/a/glfrontier/glfrontier
